# -*- coding: utf-8 -*-
"""Untitled34.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q9MLepKgQq9EWRmQNqp76JJ6kCiIZwya
"""

import os
from zoneinfo import ZoneInfo

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import psycopg2
import streamlit as st


st.set_page_config(
    page_title="NESO Wind Forecast Revision Monitor",
    page_icon="♻️",
    layout="wide"
)


# =========================
# Light styling
# =========================
st.markdown("""
<style>
    .block-container {
        padding-top: 2rem;
        padding-bottom: 2rem;
        max-width: 1400px;
    }

    div[data-testid="stSidebar"] {
        background-color: #f6f9fc;
    }

    div[data-testid="stMetric"] {
        background-color: white;
        border: 1px solid #e7eef5;
        padding: 14px 16px;
        border-radius: 16px;
        box-shadow: 0 4px 12px rgba(0, 40, 80, 0.04);
    }

    .app-title {
        font-size: 2.25rem;
        font-weight: 760;
        color: #12304a;
        margin-bottom: 0.2rem;
        line-height: 1.15;
    }

    .app-subtitle {
        font-size: 1.02rem;
        color: #486581;
        line-height: 1.55;
        margin-bottom: 0.5rem;
    }

    .badge {
        background-color: #f4f9ff;
        border: 1px solid #d8e8f5;
        border-radius: 12px;
        padding: 10px 12px;
        color: #1f425f;
        text-align: center;
        font-size: 0.88rem;
        font-weight: 600;
        min-height: 44px;
    }

    .modeller-box {
        background-color: #f8fbff;
        border-left: 4px solid #2d9cdb;
        border-radius: 10px;
        padding: 10px 14px;
        color: #35546d;
        font-size: 0.94rem;
        line-height: 1.5;
    }

    .section-title {
        font-size: 1.35rem;
        font-weight: 700;
        color: #12304a;
        margin-top: 0.8rem;
        margin-bottom: 0.75rem;
    }

    .small-muted {
        color: #627d98;
        font-size: 0.92rem;
        margin-top: -8px;
        margin-bottom: 8px;
    }

    .footer-note {
        margin-top: 22px;
        color: #627d98;
        font-size: 0.90rem;
    }
</style>
""", unsafe_allow_html=True)


# =========================
# Renewable energy SVG icon
# =========================
renewable_icon = """
<svg width="95" height="95" viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="120" y2="120">
      <stop offset="0%" stop-color="#E6F7FF"/>
      <stop offset="100%" stop-color="#E9FFF3"/>
    </linearGradient>
    <linearGradient id="panel" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#2D9CDB"/>
      <stop offset="100%" stop-color="#145DA0"/>
    </linearGradient>
  </defs>

  <rect x="4" y="4" width="112" height="112" rx="26" fill="url(#bg)" stroke="#D6EAF8" stroke-width="2"/>

  <circle cx="91" cy="29" r="10" fill="#FFD166"/>
  <path d="M91 12V7" stroke="#FFD166" stroke-width="3" stroke-linecap="round"/>
  <path d="M91 51V46" stroke="#FFD166" stroke-width="3" stroke-linecap="round"/>
  <path d="M108 29H113" stroke="#FFD166" stroke-width="3" stroke-linecap="round"/>
  <path d="M69 29H74" stroke="#FFD166" stroke-width="3" stroke-linecap="round"/>

  <line x1="41" y1="43" x2="41" y2="91" stroke="#44576D" stroke-width="4" stroke-linecap="round"/>
  <circle cx="41" cy="43" r="4" fill="#44576D"/>

  <path d="M41 43L24 35C27 26 35 22 44 25L41 43Z" fill="#57CC99"/>
  <path d="M41 43L55 27C64 32 66 42 59 51L41 43Z" fill="#2D9CDB"/>
  <path d="M41 43L35 60C25 58 19 51 20 41L41 43Z" fill="#7BC96F"/>

  <rect x="62" y="63" width="36" height="22" rx="4" fill="url(#panel)" transform="skewX(-15)"/>
  <line x1="66" y1="68" x2="99" y2="68" stroke="#CDEBFA" stroke-width="1.5"/>
  <line x1="64" y1="75" x2="97" y2="75" stroke="#CDEBFA" stroke-width="1.5"/>
  <line x1="62" y1="82" x2="95" y2="82" stroke="#CDEBFA" stroke-width="1.5"/>
  <line x1="74" y1="63" x2="69" y2="86" stroke="#CDEBFA" stroke-width="1.5"/>
  <line x1="86" y1="63" x2="81" y2="86" stroke="#CDEBFA" stroke-width="1.5"/>

  <path d="M23 93C35 85 49 84 61 91C72 97 85 97 98 90" stroke="#41B883" stroke-width="4" stroke-linecap="round"/>
</svg>
"""


# =========================
# Helpers
# =========================
LONDON_TZ = ZoneInfo("Europe/London")


def get_database_url():
    if "DATABASE_URL" in st.secrets:
        return st.secrets["DATABASE_URL"]

    database_url = os.getenv("DATABASE_URL")
    if database_url:
        return database_url

    raise RuntimeError(
        "DATABASE_URL is missing. Add it to Streamlit secrets or your environment variables."
    )


def format_dt(value, fmt="%d %b %H:%M"):
    if pd.isna(value):
        return "N/A"

    ts = pd.Timestamp(value)
    if ts.tzinfo is None:
        ts = ts.tz_localize("UTC")

    return ts.tz_convert(LONDON_TZ).strftime(fmt)


def classify_revision(abs_revision, watchlist_threshold, critical_threshold):
    if abs_revision >= critical_threshold:
        return "Critical revision"
    if abs_revision >= 1000:
        return "Major revision"
    if abs_revision >= 500:
        return "Significant revision"
    if abs_revision >= watchlist_threshold:
        return "Watchlist revision"
    if abs_revision >= 50:
        return "Minor revision"
    return "Normal movement"


@st.cache_data(ttl=300, show_spinner=False)
def load_forecast_history():
    database_url = get_database_url()

    query = """
    SELECT
        forecast_datetime,
        delivery_datetime,
        settlement_period,
        capacity_mw,
        wind_forecast_mw,
        collected_at
    FROM neso_wind_forecasts
    ORDER BY forecast_datetime, delivery_datetime
    """

    connection = psycopg2.connect(database_url)
    try:
        dataframe = pd.read_sql_query(query, connection)
    finally:
        connection.close()

    if dataframe.empty:
        return dataframe

    dataframe["forecast_datetime"] = pd.to_datetime(dataframe["forecast_datetime"], utc=True, errors="coerce")
    dataframe["delivery_datetime"] = pd.to_datetime(dataframe["delivery_datetime"], utc=True, errors="coerce")
    dataframe["collected_at"] = pd.to_datetime(dataframe["collected_at"], utc=True, errors="coerce")

    dataframe["settlement_period"] = pd.to_numeric(dataframe["settlement_period"], errors="coerce")
    dataframe["capacity_mw"] = pd.to_numeric(dataframe["capacity_mw"], errors="coerce")
    dataframe["wind_forecast_mw"] = pd.to_numeric(dataframe["wind_forecast_mw"], errors="coerce")

    dataframe = dataframe.dropna(
        subset=["forecast_datetime", "delivery_datetime", "wind_forecast_mw"]
    ).copy()

    dataframe = dataframe.sort_values(["forecast_datetime", "delivery_datetime"]).reset_index(drop=True)
    return dataframe


def build_run_summary(history_df):
    summary = (
        history_df.groupby("forecast_datetime", as_index=False)
        .agg(
            delivery_start=("delivery_datetime", "min"),
            delivery_end=("delivery_datetime", "max"),
            periods=("delivery_datetime", "count"),
            peak_forecast_mw=("wind_forecast_mw", "max"),
            average_forecast_mw=("wind_forecast_mw", "mean"),
            average_capacity_mw=("capacity_mw", "mean"),
        )
        .sort_values("forecast_datetime", ascending=False)
        .reset_index(drop=True)
    )

    summary["average_capacity_factor_pct"] = (
        summary["average_forecast_mw"] / summary["average_capacity_mw"] * 100
    ).round(1)

    return summary


def build_comparison(previous_df, latest_df):
    prev = previous_df[["delivery_datetime", "wind_forecast_mw"]].rename(
        columns={"wind_forecast_mw": "previous_forecast_mw"}
    )
    curr = latest_df[["delivery_datetime", "wind_forecast_mw"]].rename(
        columns={"wind_forecast_mw": "latest_forecast_mw"}
    )

    comparison = pd.merge(prev, curr, on="delivery_datetime", how="inner")
    comparison["revision_mw"] = comparison["latest_forecast_mw"] - comparison["previous_forecast_mw"]
    comparison["absolute_revision_mw"] = comparison["revision_mw"].abs()

    return comparison.sort_values("delivery_datetime").reset_index(drop=True)


# =========================
# Sidebar
# =========================
st.sidebar.markdown("## Controls")
st.sidebar.caption("Adjust the forecast window and revision thresholds.")

forecast_horizon_days = st.sidebar.selectbox(
    "Forecast horizon, days",
    options=list(range(1, 15)),
    index=6
)

watchlist_threshold = st.sidebar.number_input(
    "Watchlist threshold, MW",
    min_value=0,
    max_value=5000,
    value=250,
    step=50
)

critical_threshold = st.sidebar.number_input(
    "Critical swing threshold, MW",
    min_value=0,
    max_value=10000,
    value=3000,
    step=100
)

if st.sidebar.button("Refresh dashboard data"):
    st.cache_data.clear()
    st.rerun()


# =========================
# Load data
# =========================
try:
    history = load_forecast_history()
except Exception as error:
    st.error(f"Database connection failed: {error}")
    st.stop()

if history.empty:
    st.warning("No forecast records were found in the database yet.")
    st.stop()


# =========================
# Prepare datasets
# =========================
run_summary = build_run_summary(history)

distinct_runs = (
    history["forecast_datetime"]
    .drop_duplicates()
    .sort_values()
    .tolist()
)

latest_run_time = distinct_runs[-1]
previous_run_time = distinct_runs[-2] if len(distinct_runs) >= 2 else None

latest_df = history[history["forecast_datetime"] == latest_run_time].copy()

latest_delivery_start = latest_df["delivery_datetime"].min()
latest_delivery_end = latest_df["delivery_datetime"].max()
display_end = latest_delivery_start + pd.Timedelta(days=forecast_horizon_days)

latest_display_df = latest_df[
    (latest_df["delivery_datetime"] >= latest_delivery_start) &
    (latest_df["delivery_datetime"] < display_end)
].copy()

if latest_display_df.empty:
    latest_display_df = latest_df.copy()

latest_peak_mw = latest_display_df["wind_forecast_mw"].max()
latest_average_mw = latest_display_df["wind_forecast_mw"].mean()
latest_average_capacity = latest_display_df["capacity_mw"].mean()

latest_capacity_factor = (
    (latest_average_mw / latest_average_capacity) * 100
    if pd.notna(latest_average_capacity) and latest_average_capacity not in [0, None]
    else 0
)

comparison = pd.DataFrame()

if previous_run_time is not None:
    previous_df = history[history["forecast_datetime"] == previous_run_time].copy()
    comparison = build_comparison(previous_df, latest_df)

    comparison = comparison[
        (comparison["delivery_datetime"] >= latest_delivery_start) &
        (comparison["delivery_datetime"] < display_end)
    ].copy()

    if not comparison.empty:
        comparison["revision_class"] = comparison["absolute_revision_mw"].apply(
            lambda x: classify_revision(x, watchlist_threshold, critical_threshold)
        )


# =========================
# Top dashboard face card
# =========================
with st.container(border=True):
    icon_col, title_col = st.columns([1, 6], vertical_alignment="center")

    with icon_col:
        st.markdown(renewable_icon, unsafe_allow_html=True)

    with title_col:
        st.markdown(
            '<div class="app-title">NESO Wind Forecast Revision Monitor</div>',
            unsafe_allow_html=True
        )
        st.markdown(
            """
            <div class="app-subtitle">
            A lightweight, database backed dashboard for monitoring archived NESO wind forecast runs,
            run to run revision behaviour, and forward renewable energy outlook across the forecast horizon.
            </div>
            """,
            unsafe_allow_html=True
        )

        st.markdown(
            """
            <div class="modeller-box">
            <strong>Data reference:</strong> National Energy System Operator, NESO open data portal<br>
            <strong>Modeller:</strong> Kamil Ridwan Kehinde<br>
            <strong>Focus area:</strong> Renewable energy analytics, wind forecast monitoring, data intelligence and decision support
            </div>
            """,
            unsafe_allow_html=True
        )

    badge_col1, badge_col2, badge_col3, badge_col4 = st.columns(4)

    with badge_col1:
        st.markdown('<div class="badge">Renewable Energy Analytics</div>', unsafe_allow_html=True)

    with badge_col2:
        st.markdown('<div class="badge">Wind Forecast Monitoring</div>', unsafe_allow_html=True)

    with badge_col3:
        st.markdown('<div class="badge">NESO Referenced Data</div>', unsafe_allow_html=True)

    with badge_col4:
        st.markdown('<div class="badge">Streamlit and Supabase</div>', unsafe_allow_html=True)


st.info(
    "ForecastDateTime refers to when NESO published the forecast. "
    "Delivery Datetime refers to the future half hourly period being forecast. "
    "Dates beyond today therefore represent expected forecasted wind generation values, not measured actual output."
)


# =========================
# Sidebar archive information
# =========================
st.sidebar.markdown("## Database Archive")
st.sidebar.metric("Stored runs", f"{run_summary.shape[0]:,}")
st.sidebar.metric("Total forecast rows", f"{history.shape[0]:,}")
st.sidebar.write("**Newest run**")
st.sidebar.write(format_dt(latest_run_time))


# =========================
# Latest snapshot
# =========================
st.markdown('<div class="section-title">Latest NESO Forecast Snapshot</div>', unsafe_allow_html=True)

col1, col2, col3, col4 = st.columns(4)

col1.metric("Forecast Published", format_dt(latest_run_time))
col2.metric("Peak Forecast", f"{latest_peak_mw:,.0f} MW")
col3.metric("Average Forecast", f"{latest_average_mw:,.0f} MW")
col4.metric("Average Capacity Factor", f"{latest_capacity_factor:.1f}%")

st.markdown(
    f"""
    <div class="small-muted">
        Forecast delivery window, {latest_delivery_start.strftime('%Y-%m-%d %H:%M:%S%z')} to
        {latest_delivery_end.strftime('%Y-%m-%d %H:%M:%S%z')}
    </div>
    """,
    unsafe_allow_html=True
)


# =========================
# Latest forecast chart
# =========================
st.markdown('<div class="section-title">Latest NESO 14 Day Wind Forecast</div>', unsafe_allow_html=True)

latest_chart = go.Figure()
latest_chart.add_trace(
    go.Scatter(
        x=latest_display_df["delivery_datetime"],
        y=latest_display_df["wind_forecast_mw"],
        mode="lines",
        name="Latest forecast",
        line=dict(width=3, color="#2D9CDB")
    )
)

latest_chart.update_layout(
    template="plotly_white",
    height=440,
    margin=dict(l=10, r=10, t=20, b=10),
    xaxis_title="Future delivery time",
    yaxis_title="Forecasted wind generation, MW",
    legend_title="Series"
)

st.plotly_chart(latest_chart, use_container_width=True)


# =========================
# Comparison section
# =========================
if previous_run_time is not None and not comparison.empty:
    st.markdown('<div class="section-title">Run to Run Forecast Comparison</div>', unsafe_allow_html=True)

    comp_col1, comp_col2, comp_col3, comp_col4 = st.columns(4)

    largest_revision = comparison["absolute_revision_mw"].max()
    watchlist_alerts = (comparison["absolute_revision_mw"] >= watchlist_threshold).sum()

    comp_col1.metric("Previous Run", format_dt(previous_run_time))
    comp_col2.metric("Latest Run", format_dt(latest_run_time))
    comp_col3.metric("Largest Revision", f"{largest_revision:,.0f} MW")
    comp_col4.metric("Watchlist Alerts", f"{watchlist_alerts:,}")

    comparison_chart = go.Figure()

    comparison_chart.add_trace(
        go.Scatter(
            x=comparison["delivery_datetime"],
            y=comparison["previous_forecast_mw"],
            mode="lines",
            name=f"Previous run, {format_dt(previous_run_time)}",
            line=dict(width=2, color="#8DA9C4")
        )
    )

    comparison_chart.add_trace(
        go.Scatter(
            x=comparison["delivery_datetime"],
            y=comparison["latest_forecast_mw"],
            mode="lines",
            name=f"Latest run, {format_dt(latest_run_time)}",
            line=dict(width=3, color="#2D9CDB")
        )
    )

    comparison_chart.update_layout(
        template="plotly_white",
        height=440,
        margin=dict(l=10, r=10, t=20, b=10),
        xaxis_title="Forecast delivery time",
        yaxis_title="Wind forecast, MW",
        legend_title="Run"
    )

    st.plotly_chart(comparison_chart, use_container_width=True)

    st.markdown('<div class="section-title">Revision Magnitude and Alert Thresholds</div>', unsafe_allow_html=True)

    revision_chart = go.Figure()

    revision_chart.add_trace(
        go.Bar(
            x=comparison["delivery_datetime"],
            y=comparison["revision_mw"],
            name="Revision, MW",
            marker_color="#5AA9E6"
        )
    )

    revision_chart.add_hline(
        y=watchlist_threshold,
        line_dash="dash",
        line_color="#F4A261",
        annotation_text=f"Watchlist threshold, {watchlist_threshold} MW",
        annotation_position="top left"
    )
    revision_chart.add_hline(
        y=-watchlist_threshold,
        line_dash="dash",
        line_color="#F4A261"
    )

    revision_chart.add_hline(
        y=critical_threshold,
        line_dash="dot",
        line_color="#E63946",
        annotation_text=f"Critical threshold, {critical_threshold} MW",
        annotation_position="top left"
    )
    revision_chart.add_hline(
        y=-critical_threshold,
        line_dash="dot",
        line_color="#E63946"
    )

    revision_chart.update_layout(
        template="plotly_white",
        height=420,
        margin=dict(l=10, r=10, t=20, b=10),
        xaxis_title="Forecast delivery time",
        yaxis_title="Revision, MW"
    )

    st.plotly_chart(revision_chart, use_container_width=True)

    st.markdown('<div class="section-title">Watchlist and Critical Swing Alerts</div>', unsafe_allow_html=True)

    alert_col1, alert_col2 = st.columns(2)

    watchlist_df = comparison[comparison["absolute_revision_mw"] >= watchlist_threshold].copy()
    critical_df = comparison[comparison["absolute_revision_mw"] >= critical_threshold].copy()

    with alert_col1:
        st.markdown("#### Watchlist Alerts")
        if watchlist_df.empty:
            st.success("No watchlist threshold exceedances were detected in the selected forecast window.")
        else:
            watchlist_table = watchlist_df[
                [
                    "delivery_datetime",
                    "previous_forecast_mw",
                    "latest_forecast_mw",
                    "revision_mw",
                    "absolute_revision_mw",
                    "revision_class"
                ]
            ].copy()
            watchlist_table["delivery_datetime"] = watchlist_table["delivery_datetime"].dt.tz_convert(LONDON_TZ).dt.strftime("%d %b %Y %H:%M")
            watchlist_table = watchlist_table.rename(columns={
                "delivery_datetime": "Delivery Datetime",
                "previous_forecast_mw": "Previous Forecast, MW",
                "latest_forecast_mw": "Latest Forecast, MW",
                "revision_mw": "Revision, MW",
                "absolute_revision_mw": "Absolute Revision, MW",
                "revision_class": "Revision Class"
            })
            st.dataframe(watchlist_table.round(2), use_container_width=True, hide_index=True)

    with alert_col2:
        st.markdown("#### Critical Swing Alerts")
        if critical_df.empty:
            st.success("No critical swings were detected in the selected forecast window.")
        else:
            critical_table = critical_df[
                [
                    "delivery_datetime",
                    "previous_forecast_mw",
                    "latest_forecast_mw",
                    "revision_mw",
                    "absolute_revision_mw",
                    "revision_class"
                ]
            ].copy()
            critical_table["delivery_datetime"] = critical_table["delivery_datetime"].dt.tz_convert(LONDON_TZ).dt.strftime("%d %b %Y %H:%M")
            critical_table = critical_table.rename(columns={
                "delivery_datetime": "Delivery Datetime",
                "previous_forecast_mw": "Previous Forecast, MW",
                "latest_forecast_mw": "Latest Forecast, MW",
                "revision_mw": "Revision, MW",
                "absolute_revision_mw": "Absolute Revision, MW",
                "revision_class": "Revision Class"
            })
            st.dataframe(critical_table.round(2), use_container_width=True, hide_index=True)

    st.markdown('<div class="section-title">Revision Classification Summary</div>', unsafe_allow_html=True)

    class_summary = (
        comparison.groupby("revision_class", as_index=False)
        .agg(
            periods=("delivery_datetime", "count"),
            average_absolute_revision_mw=("absolute_revision_mw", "mean"),
            maximum_absolute_revision_mw=("absolute_revision_mw", "max")
        )
        .sort_values("periods", ascending=False)
    )

    if not class_summary.empty:
        class_chart = px.bar(
            class_summary,
            x="revision_class",
            y="periods",
            text="periods",
            title=None
        )
        class_chart.update_layout(
            template="plotly_white",
            height=380,
            margin=dict(l=10, r=10, t=20, b=10),
            xaxis_title="Revision class",
            yaxis_title="Number of periods"
        )
        st.plotly_chart(class_chart, use_container_width=True)

        summary_display = class_summary.rename(columns={
            "revision_class": "Revision Class",
            "periods": "Periods",
            "average_absolute_revision_mw": "Average Absolute Revision, MW",
            "maximum_absolute_revision_mw": "Maximum Absolute Revision, MW"
        }).round(2)

        st.dataframe(summary_display, use_container_width=True, hide_index=True)

else:
    st.info(
        "A run to run comparison is not available yet because the database currently contains fewer than two comparable forecast runs."
    )


# =========================
# Archive section
# =========================
st.markdown('<div class="section-title">Archived Forecast Runs</div>', unsafe_allow_html=True)

archive_display = run_summary.copy()
archive_display["forecast_datetime"] = archive_display["forecast_datetime"].apply(lambda x: format_dt(x, "%d %b %Y %H:%M"))
archive_display["delivery_start"] = archive_display["delivery_start"].apply(lambda x: format_dt(x, "%d %b %Y %H:%M"))
archive_display["delivery_end"] = archive_display["delivery_end"].apply(lambda x: format_dt(x, "%d %b %Y %H:%M"))

archive_display = archive_display.rename(columns={
    "forecast_datetime": "Forecast Published",
    "delivery_start": "Delivery Start",
    "delivery_end": "Delivery End",
    "periods": "Rows",
    "peak_forecast_mw": "Peak Forecast, MW",
    "average_forecast_mw": "Average Forecast, MW",
    "average_capacity_mw": "Average Capacity, MW",
    "average_capacity_factor_pct": "Average Capacity Factor, %"
}).round(2)

st.dataframe(archive_display, use_container_width=True, hide_index=True)


with st.expander("View latest forecast raw data"):
    latest_raw = latest_display_df.copy()
    latest_raw["forecast_datetime"] = latest_raw["forecast_datetime"].dt.tz_convert(LONDON_TZ).dt.strftime("%d %b %Y %H:%M")
    latest_raw["delivery_datetime"] = latest_raw["delivery_datetime"].dt.tz_convert(LONDON_TZ).dt.strftime("%d %b %Y %H:%M")

    if "collected_at" in latest_raw.columns:
        latest_raw["collected_at"] = latest_raw["collected_at"].dt.tz_convert(LONDON_TZ).dt.strftime("%d %b %Y %H:%M")

    latest_raw = latest_raw.rename(columns={
        "forecast_datetime": "Forecast Published",
        "delivery_datetime": "Delivery Datetime",
        "settlement_period": "Settlement Period",
        "capacity_mw": "Capacity, MW",
        "wind_forecast_mw": "Wind Forecast, MW",
        "collected_at": "Collected At"
    })

    st.dataframe(latest_raw, use_container_width=True, hide_index=True)


if previous_run_time is not None and not comparison.empty:
    with st.expander("View comparable run to run data"):
        comparison_raw = comparison.copy()
        comparison_raw["delivery_datetime"] = comparison_raw["delivery_datetime"].dt.tz_convert(LONDON_TZ).dt.strftime("%d %b %Y %H:%M")
        comparison_raw = comparison_raw.rename(columns={
            "delivery_datetime": "Delivery Datetime",
            "previous_forecast_mw": "Previous Forecast, MW",
            "latest_forecast_mw": "Latest Forecast, MW",
            "revision_mw": "Revision, MW",
            "absolute_revision_mw": "Absolute Revision, MW",
            "revision_class": "Revision Class"
        }).round(2)

        st.dataframe(comparison_raw, use_container_width=True, hide_index=True)


st.markdown("""
<div class="footer-note">
    Data source: NESO open data portal. Forecast archive stored in Supabase PostgreSQL and visualised with Streamlit.
</div>
""", unsafe_allow_html=True)